version: '3' # Указывает версию файла docker-compose

services: # Опредление сервисов
  api: # Определяет сервис api
    restart: always # Указывает, что контейнер должен всегда перезапускаться при остановке
    build: ./api # Указывает путь к директории, откуда будет собран образ для сервиса api
    ports: # Настраивает проброс портов, где 5555:5000 означает, что порт 5555 на хосте будет проброшен на порт 5000 внутри контейнера
      - 5555:5000
    depends_on: # Указывает, что сервис api зависит от сервиса mysql
      - mysql
  frontend: # Определяет сервис frontend
    restart: always # Указывает, что контейнер должен всегда перезапускаться при остановке
    build: ./frontend # Указывает путь к директории, откуда будет собран образ для сервиса frontend
    ports: # Настраивает проброс портов, где 8954:8954 означает, что порт 8954 на хосте будет проброшен на порт 8954 внутри контейнера
      - 8954:8954
  mysql: # Определяет сервис mysql
    restart: always # Указывает, что контейнер должен всегда перезапускаться при остановке
    image: mysql # Указывает, что будет использоваться образ MySQL из Docker Hub
    environment: # Задает переменные окружения для контейнера, где MYSQL_ROOT_PASSWORD устанавливает пароль для пользователя root, а MYSQL_DATABASE указывает имя базы данных
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=time_db
    volumes: # настраивает примонтирование тома, где mysql_data:/var/lib/mysql указывает, что том mysql_data будет примонтирован в /var/lib/mysql внутри контейнера
      - mysql_data:/var/lib/mysql
  adminer: # Определяет сервис adminer, который предоставляет веб-интерфейс для управления базой данных
    restart: always # Указывает, что контейнер должен всегда перезапускаться при остановке
    image: adminer # Указывает, что будет использоваться образ Adminer из Docker Hub
    ports: # Настраивает проброс портов, где 8888:8080 означает, что порт 8888 на хосте будет проброшен на порт 8080 внутри контейнера
      - 8888:8080
    depends_on: # Указывает, что сервис adminer зависит от сервиса mysql
    - mysql
volumes: # Определяет том mysql_data, который будет использоваться для хранения данных MySQL
  mysql_data: